services:
  wiremock:
    image: wiremock/wiremock:3.13.2
    container_name: mpop-wiremock
    networks:
      - hmpps_dev
    ports:
      - "8080:8080"
    volumes:
      - ./wiremock:/home/wiremock:ro

  app:
    build:
      context: .
      args:
        BUILD_NUMBER: "1.0.0"
        GIT_REF: "a1b2c3"
        GIT_BRANCH: "main"
      dockerfile: Dockerfile.feature-dev
    environment:
      - PORT=3007
      - AUDIT_ENABLED=false
      - HMPPS_AUTH_URL=http://wiremock:8080/auth
      - TOKEN_VERIFICATION_API_URL=http://wiremock:8080/verification
      - MANAGE_PEOPLE_ON_PROBATION_URL=http://wiremock:8080
      - PROBATION_FRONTEND_COMPONENTS_API_URL=http://wiremock:8080/probation-frontend-components
      - TOKEN_VERIFICATION_ENABLED=true
      - REDIS_ENABLED=false
      - NODE_ENV=development
      - AUTH_CODE_CLIENT_ID=clientid
      - AUTH_CODE_CLIENT_SECRET=clientsecret
      - CLIENT_CREDS_CLIENT_ID=clientid
      - CLIENT_CREDS_CLIENT_SECRET=clientsecret
      - ENVIRONMENT_NAME=dev
    networks:
      - hmpps_dev
    ports:
      - "3007:3007"
    depends_on:
      - wiremock

  waf:
    image: owasp/modsecurity-crs:4.25-nginx-lts
    networks:
      - hmpps_dev
    ports:
      - "8081:8080"
    environment:
      BACKEND: "http://app:3007"
      SERVER_NAME: "localhost"
      MODSEC_RULE_ENGINE: "On"
      MODSEC_AUDIT_ENGINE: "On"
      MODSEC_AUDIT_LOG: "/var/log/modsecurity/audit.log"
      MODSEC_AUDIT_LOG_TYPE: "Serial"
      BLOCKING_PARANOIA: "2"
      DETECTION_PARANOIA: "2"
    volumes:
      - ./waf-conf/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf:/etc/modsecurity.d/owasp-crs/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf:ro
      - ./waf-logs:/var/log/modsecurity
    depends_on:
      - app

networks:
  hmpps_dev:
