services:

  app:
    build:
      context: .
      args:
        BUILD_NUMBER: "1.0.0"
        GIT_REF: "a1b2c3"
        GIT_BRANCH: main
    networks:
      - hmpps
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:3000/health"]
    env_file:
      - .env

  waf:
    image: owasp/modsecurity-crs:4.25-nginx-lts
    networks:
      - hmpps
    ports:
      - "8080:8080"
    environment:
      BACKEND: "http://app:3000"
      SERVER_NAME: "localhost"
      MODSEC_RULE_ENGINE: "On"
      MODSEC_AUDIT_ENGINE: "On"
      MODSEC_AUDIT_LOG: "/var/log/modsecurity/audit.log"
      MODSEC_AUDIT_LOG_TYPE: "Serial"
      BLOCKING_PARANOIA: "2"
      DETECTION_PARANOIA: "2"
    volumes:
      - ./waf-conf/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf:/etc/modsecurity.d/owasp-crs/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf:ro
      - ./waf-logs:/var/log/modsecurity
    depends_on:
      - app

networks:
  hmpps:
